@baseUrl = http://localhost:8081/api

### Get All Categories
GET {{baseUrl}}/categories
Content-Type: application/json

### Get Category by ID
GET {{baseUrl}}/categories/347af1cb-1751-4dfb-828e-b8840ec621ccdddd
Content-Type: application/json

### Create Category
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "name": "John Doe",
    "email": "c@com",
    "password": "123456"
}
  