ARG API_PORT
ARG SERVICE_NAME
ARG CNPJ_FINDER_URL
ARG CNPJ_FINDER_TIMEOUT

FROM golang:1.25.5

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o tmp/main ./cmd/server

EXPOSE 8080

CMD ["air"]