# .build/dev/Dockerfile.dev
FROM node:22-alpine

# Pasta da aplicação
WORKDIR /app

# Copia apenas package.json / package-lock.json para aproveitar cache
COPY package*.json ./

# Instala todas as dependências (incluindo dev)
RUN npm install

# Copia o restante do código
COPY . .

# Expõe a porta da API
EXPOSE 3001

# Comando de desenvolvimento (hot reload)
CMD ["npm", "run", "dev"]
